
spring:
  application:
    name: api-player-v1
  data:
    mongodb:
      #host: localhost
      #port: 27017
      uri: mongodb://geopagos-mongodb:KcL4FI1BxfwlPJ3XNkwZXXLzhY8VZWubzQ5WIdvSTTGoG4wjJxky8ev2Fp6fF5AsRwibgYMHRgtlACDbiHASxA==@geopagos-mongodb.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@geopagos-mongodb@
      database: player
